name: Deploy

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "README*"
  pull_request:

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Set up JDK 21"
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: "Cache local Maven repository"
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ secrets.workload_identity_provider }}
          service_account: ${{ secrets.service_account }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Build with Maven"
        run: ./mvnw install -DskipTests=true

      - name: "Deploy to Cloud Function"
        run: |
          gcloud functions deploy ${{ secrets.cloud_function_name }} \
            --entry-point io.quarkus.gcp.functions.QuarkusHttpFunction \
            --runtime java21 \
            --trigger-http \
            --allow-unauthenticated \
            --source target/deployment \
            --service-account ${{ secrets.cloud_function_service_account }} \
            --region=europe-west9 \
            --gen2